set(SRC_FILES
    Animator.cpp
    App.cpp
    AudioManager.cpp
    Background.cpp
    Button.cpp
    Character.cpp
    Coin.cpp
    Collider.cpp
    CollisionHandler.cpp
    Door.cpp
    DoorButton.cpp
    EscButton.cpp
    InputHandler.cpp
    Level1.cpp
    Level2.cpp
    Level4.cpp
    LevelButton.cpp
    LevelSelect.cpp
    MovableSprite.cpp
    Rigidbody.cpp
    SoundEffect.cpp
    Spike.cpp
    Spring.cpp
    Sprite.cpp
    Transition.cpp
    TriggerCollider.cpp
)

set(INCLUDE_FILES
    Animator.hpp
    App.hpp
    AudioManager.hpp
    Background.hpp
    Button.hpp
    Character.hpp
    Coin.hpp
    Collider.hpp
    CollisionHandler.hpp
    Door.hpp
    DoorButton.hpp
    EasingFunction.hpp
    EscButton.hpp
    IBehaviour.hpp
    ILevel.hpp
    InputHandler.hpp
    Level.hpp
    Level1.hpp
    Level2.hpp
    Level4.hpp
    LevelButton.hpp
    LevelSelect.hpp
    MovableSprite.hpp
    Rigidbody.hpp
    SoundEffect.hpp
    Spike.hpp
    Spring.hpp
    Sprite.hpp
    Transition.hpp
    TriggerCollider.hpp
)

set(TEST_FILES
)
